# Generated by Django 3.2.5 on 2021-07-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffappraisal', '0002_alter_appraiserandappraiseeagreement_super_visor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraiserandappraiseeagreement',
            name='agreed_rating',
        ),
    ]
