# Generated by Django 3.2.5 on 2021-07-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffappraisal', '0003_remove_appraiserandappraiseeagreement_agreed_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='agreed_action',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='performance_gap',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
