# Generated by Django 3.2.5 on 2021-08-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffappraisal', '0005_alter_appraiseecomment_competence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='faculty_name',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='department_name',
            new_name='department',
        ),
    ]
