# Generated by Django 3.2.5 on 2021-08-24 12:47

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staffappraisal', '0006_auto_20210814_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraiserandappraiseeagreement',
            name='super_visor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Supervisor inspecting this.'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='time_frame',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('120'))], verbose_name='Time duration in days'),
        ),
    ]
