# Generated by Django 3.2.5 on 2021-08-24 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staffappraisal', '0007_auto_20210824_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraiserandappraiseeagreement',
            name='super_visor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Supervisor inspecting this.'),
        ),
    ]
