# Generated by Django 3.2.5 on 2021-09-03 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staffappraisal', '0008_alter_appraiserandappraiseeagreement_super_visor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraiserandappraiseeagreement',
            name='super_visor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Supervisor inspecting this.'),
        ),
    ]
