# Generated by Django 3.2.5 on 2021-09-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffappraisal', '0009_alter_appraiserandappraiseeagreement_super_visor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisercomment',
            name='appraisee_comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staffappraisal.appraiseecomment'),
        ),
    ]
